name: movie_advisor
description: "Discover, track, and get personalized recommendations for movies and TV shows effortlessly."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.2+7

environment:
  sdk: ^3.7.2
  flutter: ^3.29.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # UI
  theme_tailor_annotation: ^3.0.2
  skeletonizer: ^1.4.3
  flutter_animate: ^4.5.2
  extended_image: ^10.0.1
  go_router: ^15.1.1
  keyboard_actions: ^4.2.0
  flutter_form_builder: ^10.0.1
  flutter_hooks: ^0.21.2
  flutter_native_splash: ^2.4.6
  easy_localization: ^3.0.7+1
  flutter_svg: ^2.1.0
  sliver_tools: ^0.2.12
  url_launcher: ^6.3.1
  fluttertoast: ^8.2.12
  animated_toggle_switch: ^0.8.4
  flutter_keyboard_visibility: ^6.0.0
  upgrader: ^11.3.1
  filter_list: ^1.0.3

  # General
  intl: any
  collection: any
  async: any
  flutter_utils:
    git:
      url: https://github.com/valeriinov/flutter_utils.git
      ref: 1.2.0

  # Architecture
  hooks_riverpod: ^2.6.1
  dart_mappable: ^4.5.0
  dartz: ^0.10.1
  class_namer_annotation:
    git:
      url: https://github.com/valeriinov/class_namer.git
      path: packages/class_namer_annotation
      ref: main

  # Network
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  flutter_dotenv: ^5.2.1
  connectivity_plus: ^6.1.3

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  cloud_functions: ^5.4.0

  # Local storage
  drift: ^2.26.0
  drift_flutter: ^0.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  theme_tailor: ^3.0.2
  build_runner: ^2.4.15
  dart_mappable_builder: ^4.5.0
  go_router_builder: ^2.8.2
  build_verify: ^3.1.0
  flutter_flavorizr: ^2.3.1
  drift_dev: ^2.26.0
  class_namer:
    git:
      url: https://github.com/valeriinov/class_namer.git
      path: packages/class_namer
      ref: main

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/montserrat/Montserrat-ThinItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/montserrat/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraBoldItalic.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans_SemiCondensed-MediumItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans_SemiCondensed-Regular.ttf
        - asset: assets/fonts/open_sans/OpenSans-SemiBold.ttf
        - asset: assets/fonts/open_sans/OpenSans_SemiCondensed-Bold.ttf
        - asset: assets/fonts/open_sans/OpenSans_Condensed-Medium.ttf
        - asset: assets/fonts/open_sans/OpenSans_SemiCondensed-Light.ttf
        - asset: assets/fonts/open_sans/OpenSans_Condensed-ExtraBold.ttf
        - asset: assets/fonts/open_sans/OpenSans_SemiCondensed-SemiBoldItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans_Condensed-SemiBold.ttf
        - asset: assets/fonts/open_sans/OpenSans_SemiCondensed-SemiBold.ttf
        - asset: assets/fonts/open_sans/OpenSans_Condensed-LightItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans_Condensed-Bold.ttf
        - asset: assets/fonts/open_sans/OpenSans-Light.ttf
        - asset: assets/fonts/open_sans/OpenSans-Italic.ttf
        - asset: assets/fonts/open_sans/OpenSans_SemiCondensed-Medium.ttf
        - asset: assets/fonts/open_sans/OpenSans-MediumItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans_Condensed-Light.ttf
        - asset: assets/fonts/open_sans/OpenSans_Condensed-SemiBoldItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans_SemiCondensed-ExtraBold.ttf
        - asset: assets/fonts/open_sans/OpenSans_Condensed-BoldItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/open_sans/OpenSans-LightItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans_SemiCondensed-LightItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
        - asset: assets/fonts/open_sans/OpenSans_Condensed-MediumItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans_SemiCondensed-Italic.ttf
        - asset: assets/fonts/open_sans/OpenSans-SemiBoldItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans-Medium.ttf
        - asset: assets/fonts/open_sans/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
        - asset: assets/fonts/open_sans/OpenSans_SemiCondensed-BoldItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans_Condensed-Regular.ttf
        - asset: assets/fonts/open_sans/OpenSans_Condensed-ExtraBoldItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans_Condensed-Italic.ttf
        - asset: assets/fonts/open_sans/OpenSans_SemiCondensed-ExtraBoldItalic.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
        - asset: assets/fonts/roboto/Roboto-Light.ttf
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-MediumItalic.ttf
        - asset: assets/fonts/roboto/Roboto-ThinItalic.ttf
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
        - asset: assets/fonts/roboto/Roboto-LightItalic.ttf
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
        - asset: assets/fonts/roboto/Roboto-BlackItalic.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
        - asset: assets/fonts/roboto/Roboto-Black.ttf

  assets:
    - assets/images/
    - assets/translations/
    - dev.env
    - prod.env

# To use scripts:
# 1. Install rps: dart pub global activate rps
# 2. Use your custom command: rps gen
# You can also provide additional arguments: rps gen --verbose
scripts:
  gen: dart run build_runner build --delete-conflicting-outputs
  aabDev: flutter build appbundle --flavor dev -t lib/main_dev.dart
  apkDev: flutter build apk --flavor dev -t lib/main_dev.dart
  runDev: flutter run --flavor dev -t lib/main_dev.dart
  aabProd: flutter build appbundle --flavor prod -t lib/main_prod.dart
  apkProd: flutter build apk --flavor prod -t lib/main_prod.dart
  runProd: flutter run --flavor prod -t lib/main_prod.dart
  genLocaleKeys: dart run easy_localization:generate -f keys -o locale_keys.g.dart -O "lib/view/ui/resources" -S "assets/translations"
  genDto: mason make dto
  genEntity: mason make entity
  genRepo: mason make repo --arch mvvm_riverpod
  genScene: mason make riverpod_scene
  updFonts: mason make upd_fonts
  updImages: mason make upd_images

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
